name: Laravel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up the environment file
      - name: Set up .env file
        working-directory: ./api
        run: |
          if [ -f .env.example ]; then
            cp .env.example .env
          else
            echo "APP_KEY=" > .env
            echo "DB_CONNECTION=sqlite" >> .env
            echo "DB_DATABASE=/path/to/api/database/database.sqlite" >> .env
          fi

      # Step 3: Set up PHP and required extensions
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, pdo_sqlite, bcmath, fileinfo, openssl
          tools: composer

      # Step 4: Cache Composer packages
      - name: Cache Composer Dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: api/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('api/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Step 5: Install dependencies
      - name: Install Dependencies
        working-directory: ./api
        run: composer install --no-ansi --no-interaction --prefer-dist

      # Step 6: Generate application key
      - name: Generate Application Key
        working-directory: ./api
        run: php artisan key:generate

      # Step 7: Set up the SQLite database
      - name: Set up SQLite Database
        working-directory: ./api
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Step 8: Run database migrations
      - name: Run Migrations
        working-directory: ./api
        run: php artisan migrate --force

      # Step 9: Run Laravel Tests
      - name: Run Tests
        working-directory: ./api
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

