name: Laravel API in bca Folder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer # Ensure Composer is installed

    # Step 2: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 3: Navigate to the `bca` folder
    - name: Set working directory
      working-directory: ./bca
      run: echo "Working directory set to $(pwd)"

    # Step 4: Set up the environment file
    - name: Set up environment file
      run: |
        if [ ! -f .env ]; then
          cp .env.example .env
        fi

    # Step 5: Install dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Step 6: Generate application key
    - name: Generate Application Key
      run: php artisan key:generate

    # Step 7: Set directory permissions
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Step 8: Create SQLite database
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    # Step 9: Run migrations
    - name: Run Migrations
      run: php artisan migrate --force

    # Step 10: Run tests
    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
